# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sierralingo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sierralingo
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Toast-Swift', '~> 2.0.0'
  pod 'Alamofire', '~> 4.4'
  pod 'MLVerticalProgressView'
  pod 'ReachabilitySwift', '~> 3'
  pod 'IQKeyboardManagerSwift', '4.0.8'
  pod 'UICircularProgressRing'
  pod ‘NVActivityIndicatorView’

  target 'SierralingoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SierralingoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
